name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Frontend to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # ไปที่โฟลเดอร์โปรเจคบน Server
            cd /home/dserver/share_folder/application/TrendCart_Project/frontend
            git pull origin main
            
            cd ..
            # Rebuild only the frontend service
            docker compose build trendcart_frontend
            docker compose up -d trendcart_frontend
